stages:
  - build
  - test
  - release

compile:
  stage: build
  image: golang:1.15.3-alpine
  script:
    - go build ./cmd/draid

test:
  stage: test
  image: golang:1.15.3
  script:
  - go test -cover ./...

formatting:
  stage: test
  image: golang:1.15.3-alpine
  script:
  - test $(gofmt -l | wc -l) -eq 0

vet:
  stage: test
  image: golang:1.15.3
  script:
  - go vet ./...

lint:
  stage: test
  image: golang:1.15.3
  before_script:
  - GO111MODULE=off go get golang.org/x/lint/golint
  script:
  - golint -set_exit_status .

release-nightly:
  stage: release
  image:
    name: goreleaser/goreleaser:v0.101.0
    entrypoint: ["/bin/sh", "-c"]
  script:
  - goreleaser release --snapshot --skip-publish
  artifacts:
    paths:
      - dist/*.tar.gz
    expire_in: 1 week
  only:
  - master

release:
  stage: release
  image:
    name: goreleaser/goreleaser:v0.101.0
    entrypoint: ["/bin/sh", "-c"]
  script:
  - goreleaser release --skip-publish
  artifacts:
    paths:
      - dist/*.tar.gz
  only:
  - tags